=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/viewer/src/assets/schemas/wallet.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Wallet",
  "title": "Wallet or Agent",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the agent JSON entry"
    },
    "name": {
      "type": "string",
      "description": "The name of the agent"
    },
    "urlWebsite": {
      "type": "string",
      "description": "An URL to the website of the agent with more information",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "description": "The URL to the logo of the agent"
    },
    "company": {
      "type": "string",
      "description": "The name of the company or a community developing the agent"
    },
    "companyUrl": {
      "type": "string",
      "description": "The url to the company website (not the product website)",
      "format": "uri"
    },
    "contact": {
      "type": "string",
      "description": "A link to a contact form or an email address for support requests"
    },
    "openSource": {
      "type": "boolean",
      "description": "The agent source code is available under an open-source license"
    },
    "downloadSource": {
      "type": "string",
      "description": "The URL to the source code, for example a github repository",
      "format": "uri"
    },
    "license": {
      "type": "string",
      "description": "The license(s) of the agent source code."
    },
    "capability": {
      "type": "array",
      "description": "The capabilities supported by the agent",
      "items": {
        "type": "string",
        "enum": ["holder", "issuer", "verifier"]
      }
    },
    "executionEnvironment":  {
      "type": "string",
      "description": "Execution environment of an agent is the place where the agent is intended to be run",
      "enum": ["cloud", "edge"]
    },
    "portability": {
      "type": "boolean",
      "description": "Users can export their data from the agent and import them into another device/system"
    },
    "urlAppStore": {
      "type": "string",
      "description": "Link to the Apple AppStore",
      "format": "uri"
    },
    "urlGooglePlayStore": {
      "type": "string",
      "description": "Link to the Google Play store",
      "format": "uri"
    },
    "urlWebApp": {
      "type": "string",
      "description": "Link to the web app - where the agent can be used with a browser",
      "format": "uri"
    },
    "dependencies": {
      "type": "array",
      "description": "List of dependencies required to run the agent",
      "items": {
        "$comment": "it would help to use an enum here, but this job has to be run by each change so the enum gets updated for a valid test.",
        "type": "string"
      }
    },
    "credentialProfiles": {
      "type": "array",
      "description": "List of supported credential profiles. They entries must be valid credential profiles defined by the Credential Profiles Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Credential-Profile"
      }
    },
    "credentialFormats": {
      "type": "array",
      "description": "List of supported credential formats. They entries must be valid credential formats defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Credential%20Format",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Credential-Format"
      }
    },
    "signingAlgorithms": {
      "type": "array",
      "description": "List of supported signing algorithms. The entries must be valid algorithms defined by the Credential Formats Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Signing%20Algorithm",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Signing-Algorithm"
      }
    },
    "statusManagements": {
      "type": "array",
      "description": "List of supported status management methods. The entries must be valid status management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Status%20Algorithm",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Status-Algorithm"
      }
    },
    "keyManagements": {
      "type": "array",
      "description": "List of supported key management methods. The entries must be valid key management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Key%20Management",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Key-Management"
      }
    },
    "issuanceProtocols": {
      "type": "array",
      "description": "List of supported issuance protocols. The entries must be valid issuance protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Issuance%20Protocol",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Issuance-Protocol"
      }
    },
    "presentationProtocols": {
      "type": "array",
      "description": "List of supported presentation protocols. The entries must be valid presentation protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Presentation%20Protocol",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Presentation-Protocol"
      }
    },
    "trustManagements": {
      "type": "array",
      "description": "List of supported trust management methods. The entries must be valid trust management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Trust%20Management",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Trust-Management"
      }
    }
  },
  "required": ["capability", "company", "name", "urlWebsite"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/authada.json
{
  "capability": [
    "issuer",
    "verifier"
  ],
  "name": "AUTHADA wallet platform",
  "logo": "https://authada.de/wp-content/uploads/2022/02/authada-logo.svg",
  "company": "AUTHADA GmbH",
  "companyUrl": "https://authada.de/",
  "urlWebsite": "https://authada.de/loesungen/wallet-platform/",
  "openSource": false,
  "portability": false,
  "credentialProfiles": [
    "HAIP",
    "ISO mDL",
    "SD-JWT VCs (w/ X.509 for Issuers)",
    "x.509"
  ],
  "credentialFormats": [
    "MDOC",
    "SD-JWT VC",
    "x509"
  ],
  "issuanceProtocols": [
    "OpenID4VCI"
  ],
  "keyManagements": [
    "jwks_uri",
    "pub key in X.509 cert",
    "raw public keys (jwk)"
  ],
  "presentationProtocols": [
    "OpenID4VP"
  ],
  "signingAlgorithms": [
    "ECDSA"
  ],
  "statusManagements": [
    "Token Status List (TSL)"
  ],
  "trustManagements": [
    "Trusted Lists",
    "Verified issuer certificate authority list (VICAL)",
    "X.509 certificates"
  ],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/gataca-studio.json
{
  "capability": ["issuer", "verifier"],
  "company": "Gataca Inc.",
  "credentialFormats": ["LDP-VC", "JWT-VC"],
  "credentialProfiles": ["EBSI"],
  "issuanceProtocols": ["OpenID4VCI"],
  "keyManagements": ["did:key"],
  "logo": "logos/gataca.png",
  "name": "Gataca Studio",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["EdDSA", "RSA"],
  "statusManagements": ["Status List 2021"],
  "executionEnvironment": "cloud",
  "urlWebsite": "https://gataca.io/products/gatacaStudio/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/farmworker-wallet-os.json
{
  "capability": [
    "holder"
  ],
  "executionEnvironment":"edge",
  "name": "Farmworker Wallet OS",
  "logo": "https://cdn.prod.website-files.com/6520979d785cc136404a270d/65237d6a3505e25d76ed58c7_wallet-p-1080.png",
  "company": " Entidad",
  "companyUrl": "https://www.entidad.io",
  "urlWebsite": "https://www.farmworkerwalletos.community/",
  "downloadSource": "https://github.com/openwallet-foundation-labs/farmworker-wallet-os",
  "openSource": true,
  "license": "Apache 2.0",
  "portability": false,
  "credentialProfiles": [
    "AnonCreds with did:indy",
    "AnonCreds with did:web"
  ],
  "credentialFormats": [
    "AnonCred"
  ],
  "issuanceProtocols": [],
  "keyManagements": [
    "did:indy",
    "did:jwk",
    "did:key",
    "did:peer",
    "did:web",
    "raw public keys (jwk)"
  ],
  "presentationProtocols": [
    "Present Proof v2",
    "Present Proof v1.0"
  ],
  "signingAlgorithms": [
    "CL",
    "ECDSA",
    "EdDSA"
  ],
  "statusManagements": [],
  "trustManagements": [],
  "dependencies": [
    "credo"
  ],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/microsoft-entra.json
{
  "capability": ["issuer", "verifier"],
  "company": "Microsoft",
  "credentialFormats": ["JWT-VC"],
  "keyManagements": ["did:web"],
  "logo": "logos/microsoft-entra.png",
  "name": "Microsoft Entra Verified ID",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "statusManagements": ["Status List 2021"],
  "executionEnvironment":"cloud",
  "urlWebsite": "https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-verified-id"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/procivis-one-core.json
{
  "name": "Procivis One Core",
  "logo": "logos/procivis-one-core.png",
  "company": "Procivis AG",
  "companyUrl": "https://www.procivis.ch",
  "executionEnvironment": "edge",
  "openSource": true,
  "license": "Apache-2.0",
  "capability": ["issuer", "verifier", "holder"],
  "portability": true,
  "urlWebsite": "https://www.procivis.ch/",
  "urlWebApp": "https://docs.procivis.ch",
  "downloadSource": "https://github.com/procivis/one-core",
  "credentialProfiles": ["ISO mDL", "JSON-LD VCs with BBS (Holder DID)"],
  "credentialFormats": ["JWT-VC", "JWT", "LDP-VC", "MDOC", "SD-JWT", "SD-JWT VC", "VCDM 1.1", "VCDM 2.0", "x509"],
  "issuanceProtocols": ["OpenID4VCI", "ISO 23220-3"],
  "keyManagements": ["did:jwk", "did:key", "did:web", "pub key in X.509 cert", "cose key", "did:webvh"],
  "presentationProtocols": ["OpenID4VP"],
  "signingAlgorithms": ["BBS+ with public key binding", "ECDSA", "EdDSA", "ML-DSA"],
  "statusManagements": ["Status List 2021"],
  "trustManagements": ["Trusted Lists", "List of Trusted Lists (LoTL)", "List of Trusted Entities (LoTE)"],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/jssoft-frosch-wallet.json
{
  "capability": [
    "holder"
  ],
  "executionEnvironment": "edge",
  "name": "Frosch Wallet",
  "logo": "https://www.js-soft.com/wp-content/uploads/2022/03/Logo-js-soft.png",
  "company": "j&s-soft AG",
  "companyUrl": "https://www.js-soft.com/",
  "urlWebsite": "https://www.js-soft.com/wallets/",
  "urlAppStore": "https://apps.apple.com/es/app/frosch-wallet/id6756783868?l=en-GB",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=app.frosch.prod&hl=de",
  "openSource": false,
  "portability": true,
  "credentialProfiles": [
    "SD-JWT VCs (w/ X.509 for Issuers)",
    "x.509"
  ],
  "credentialFormats": [
    "MDOC",
    "SD-JWT VC",
    "SD-JWT"
  ],
  "issuanceProtocols": [
    "OpenID4VCI"
  ],
  "keyManagements": [
    "did:cheqd",
    "did:jwk",
    "did:key",
    "did:web",
    "did:webvh",
    "pub key in X.509 cert",
    "raw public keys (jwk)",
    "raw public keys (none jwk)"
  ],
  "presentationProtocols": [
    "OpenID4VP"
  ],
  "signingAlgorithms": [
    "ECDSA",
    "EdDSA"
  ],
  "statusManagements": [
    "Token Status List (TSL)"
  ],
  "trustManagements": [
    "Verifier knows Issuers",
    "X.509 certificates"
  ],
  "dependencies": [
    "credo"
  ],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/entidad-unmio.json
{
  "capability": [
    "issuer",
    "verifier"
  ],
  "executionEnvironment": "cloud",
  "name": "Unmio",
  "logo": "https://unmio-ecosystem-assets.s3.us-west-1.amazonaws.com/images/Unmio_Logo_Green-Color.png",
  "company": "Entidad",
  "companyUrl": "https://www.entidad.io",
  "contact": "info@unmio.com",
  "urlWebsite": "https://www.unmio.com",
  "openSource": false,
  "license": "Commercial",
  "portability": false,
  "credentialProfiles": [
    "AnonCreds with did:indy",
    "AnonCreds with did:web"
  ],
  "credentialFormats": [
    "AnonCred"
  ],
  "issuanceProtocols": [
    "Issue Credential v2"
  ],
  "keyManagements": [
    "did:key",
    "did:web",
    "did:peer"
  ],
  "presentationProtocols": [
    "Present Proof v2",
    "Present Proof v1.0"
  ],
  "dependencies": [
    "farmworker-wallet-os"
  ],
  "signingAlgorithms": [
    "CL",
    "ECDSA",
    "EdDSA"
  ],
  "statusManagements": [
    "Indy Revocation"
  ],
  "trustManagements": [],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/authenticator.json
{
  "capability": ["holder"],
  "company": "Microsoft",
  "credentialFormats": ["JWT-VC"],
  "keyManagements": ["did:web"],
  "logo": "logos/authenticator.png",
  "name": "Authenticator",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "edge",
  "urlAppStore": "https://go.microsoft.com/fwlink/p/?linkid=2168643&clcid=0x409",
  "urlGooglePlayStore": "https://go.microsoft.com/fwlink/p/?linkid=2168850&clcid=0x409",
  "urlWebsite": "https://www.microsoft.com/en-us/security/mobile-authenticator-app"
}
