=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/viewer/src/assets/schemas/wallet.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Wallet",
  "title": "Wallet or Agent",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the agent JSON entry"
    },
    "name": {
      "type": "string",
      "description": "The name of the agent"
    },
    "urlWebsite": {
      "type": "string",
      "description": "An URL to the website of the agent with more information",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "description": "The URL to the logo of the agent"
    },
    "company": {
      "type": "string",
      "description": "The name of the company or a community developing the agent"
    },
    "companyUrl": {
      "type": "string",
      "description": "The url to the company website (not the product website)",
      "format": "uri"
    },
    "contact": {
      "type": "string",
      "description": "A link to a contact form or an email address for support requests"
    },
    "openSource": {
      "type": "boolean",
      "description": "The agent source code is available under an open-source license"
    },
    "downloadSource": {
      "type": "string",
      "description": "The URL to the source code, for example a github repository",
      "format": "uri"
    },
    "license": {
      "type": "string",
      "description": "The license(s) of the agent source code."
    },
    "capability": {
      "type": "array",
      "description": "The capabilities supported by the agent",
      "items": {
        "type": "string",
        "enum": ["holder", "issuer", "verifier"]
      }
    },
    "executionEnvironment":  {
      "type": "string",
      "description": "Execution environment of an agent is the place where the agent is intended to be run",
      "enum": ["cloud", "edge"]
    },
    "portability": {
      "type": "boolean",
      "description": "Users can export their data from the agent and import them into another device/system"
    },
    "urlAppStore": {
      "type": "string",
      "description": "Link to the Apple AppStore",
      "format": "uri"
    },
    "urlGooglePlayStore": {
      "type": "string",
      "description": "Link to the Google Play store",
      "format": "uri"
    },
    "urlWebApp": {
      "type": "string",
      "description": "Link to the web app - where the agent can be used with a browser",
      "format": "uri"
    },
    "dependencies": {
      "type": "array",
      "description": "List of dependencies required to run the agent",
      "items": {
        "$comment": "it would help to use an enum here, but this job has to be run by each change so the enum gets updated for a valid test.",
        "type": "string"
      }
    },
    "credentialProfiles": {
      "type": "array",
      "description": "List of supported credential profiles. They entries must be valid credential profiles defined by the Credential Profiles Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Credential-Profile"
      }
    },
    "credentialFormats": {
      "type": "array",
      "description": "List of supported credential formats. They entries must be valid credential formats defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Credential%20Format",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Credential-Format"
      }
    },
    "signingAlgorithms": {
      "type": "array",
      "description": "List of supported signing algorithms. The entries must be valid algorithms defined by the Credential Formats Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Signing%20Algorithm",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Signing-Algorithm"
      }
    },
    "statusManagements": {
      "type": "array",
      "description": "List of supported status management methods. The entries must be valid status management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Status%20Algorithm",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Status-Algorithm"
      }
    },
    "keyManagements": {
      "type": "array",
      "description": "List of supported key management methods. The entries must be valid key management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Key%20Management",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Key-Management"
      }
    },
    "issuanceProtocols": {
      "type": "array",
      "description": "List of supported issuance protocols. The entries must be valid issuance protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Issuance%20Protocol",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Issuance-Protocol"
      }
    },
    "presentationProtocols": {
      "type": "array",
      "description": "List of supported presentation protocols. The entries must be valid presentation protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Presentation%20Protocol",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Presentation-Protocol"
      }
    },
    "trustManagements": {
      "type": "array",
      "description": "List of supported trust management methods. The entries must be valid trust management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Trust%20Management",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Trust-Management"
      }
    }
  },
  "required": ["capability", "company", "name", "urlWebsite"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/sowl.json
{
  "capability": ["issuer", "verifier"],
  "company": "esatus AG",
  "credentialFormats": ["AnonCred"],
  "credentialProfiles": ["AnonCreds with did:indy"],
  "logo": "logos/esatus-wallet.png",
  "name": "SOWL",
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "cloud",
  "urlWebsite": "https://esatus.com/en/digital-identity/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/vidua.json
{
  "capability": ["holder"],
  "company": "Cleverbase",
  "credentialFormats": ["x509", "JWT"],
  "contact": "klantenservice@vidua.nl",
  "issuanceProtocols": ["OpenID4VCI"],
  "logo": "logos/vidua.png",
  "name": "Vidua",
  "openSource": false,
  "portability": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["ECDSA", "RSA"],
  "executionEnvironment": "edge",
  "urlAppStore": "https://apps.apple.com/en/app/vidua/id6443842104",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=nl.vidua.wallet",
  "urlWebsite": "https://vidua.nl/english/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/anonyome-wallet.json
{
  "capability": ["holder"],
  "executionEnvironment":"edge",
  "name": "Anonyome Mobile Wallet",
  "logo": "logos/anonyome.png",
  "company": "Anonyome Labs",
  "companyUrl": "https://www.anonyome.com",
  "urlWebsite": "https://sudoplatform.com/identity-wallet/",
  "openSource": false,
  "license": "",
  "credentialProfiles": ["AnonCreds with did:indy"],
  "credentialFormats": ["AnonCred", "LDP-VC", "VC (1.1)", "SD-JWT-VC", "SD-JWT"],
  "issuanceProtocols": ["Issue Credential v1", "Issue Credential v2", "OpenID4VCI"],
  "keyManagements": ["did:indy", "did:key", "did:peer", "link secrets"],
  "presentationProtocols": ["Present Proof v2", "Present Proof v1.0", "OpenID4VP"],
  "signingAlgorithms": ["BBS+ with public key binding", "CL", "ECDSA", "EdDSA"],
  "statusManagements": ["Indy Revocation"],
  "trustManagements": [],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/wwwallet.json
{
  "capability": ["holder"],
  "company": "GUnet",
  "credentialFormats": ["JWT-VC"],
  "credentialProfiles": ["EBSI"],
  "downloadSource": "https://github.com/wwWallet",
  "logo": "logos/wwwallet.png",
  "name": "wwWallet",
  "openSource": true,
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "cloud",
  "urlWebApp": "https://demo.wwwallet.org/",
  "urlWebsite": "https://wwwallet.github.io/wallet-docs/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/spherity-wallet.json
{
  "capability": ["issuer", "holder", "verifier"],
  "company": "Spherity GmbH",
  "credentialFormats": ["LDP-VC"],
  "issuanceProtocols": ["Issue Credential v3"],
  "logo": "logos/spherity-wallet.png",
  "name": "Spherity Wallet",
  "openSource": false,
  "presentationProtocols": ["Presentation Exchange v1"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["BBS+ with public key binding", "ECDSA", "EdDSA", "RSA"],
  "statusManagements": ["Status List 2021"],
  "executionEnvironment":"cloud",
  "urlWebsite": "https://www.spherity.com/enterprise-identity-wallet"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/dock-wallet.json
{
  "capability": ["holder"],
  "company": "Dock",
  "contact": "marketing@dock.io",
  "downloadSource": "https://github.com/docknetwork/universal-wallet",
  "name": "Dock Wallet",
  "$schema": "../../schemas/wallet.json",
  "executionEnvironment": "edge",
  "urlAppStore": "https://apps.apple.com/ph/app/dock-wallet/id1565227368",
  "urlGooglePlayStore": "https://play.google.com/store/apps/details?id=com.dockapp",
  "urlWebsite": "https://www.dock.io/dock-wallet-app"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/jssoft-froschWork.json
{
  "capability": [
    "issuer",
    "verifier"
  ],
    "executionEnvironment": "edge",
  "name": "Frosch Work",
  "logo": "https://www.js-soft.com/wp-content/uploads/2022/03/Logo-js-soft.png",
  "company": "j&s-soft AG",
  "companyUrl": "https://www.js-soft.com/",
  "urlWebsite": "https://www.js-soft.com/wallets/",
  "openSource": false,
  "portability": false,
  "credentialProfiles": [
    "SD-JWT VCs (w/ X.509 for Issuers)",
    "x.509"
  ],
  "credentialFormats": [
    "MDOC",
    "SD-JWT VC",
    "SD-JWT"
  ],
  "issuanceProtocols": [
    "OpenID4VCI"
  ],
  "keyManagements": [
    "did:cheqd",
    "did:jwk",
    "did:key",
    "did:web",
    "did:webvh",
    "pub key in X.509 cert",
    "raw public keys (jwk)",
    "raw public keys (none jwk)"
  ],
  "presentationProtocols": [
    "OpenID4VP"
  ],
  "signingAlgorithms": [
    "ECDSA",
    "EdDSA"
  ],
  "statusManagements": [
    "Token Status List (TSL)"
  ],
  "trustManagements": [
    "Verifier knows Issuers",
    "X.509 certificates"
  ],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/paradym.json
{
  "$schema": "../../schemas/wallet.json",
  "capability": ["issuer", "verifier"],
  "company": "Animo Solutions",
  "contact": "ana@paradym.id",
  "credentialFormats": ["AnonCred", "SD-JWT VC", "MDOC"],
  "issuanceProtocols": ["OpenID4VCI", "Issue Credential v2"],
  "keyManagements": ["did:jwk", "did:key", "did:web", "did:cheqd", "did:webvh"],
  "logo": "logos/paradym-wallet.png",
  "name": "Paradym",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP", "Present Proof v2"],
  "signingAlgorithms": ["EdDSA", "ECDSA"],
  "statusManagements": ["Token Status List (TSL)", "Indy Revocation"],
  "dependencies": ["credo", "sd-jwt-js"],
  "credentialProfiles": ["DIIP", "HAIP", "ISO mDL", "SD-JWT VCs (w/ X.509 for Issuers)", "AnonCreds with did:cheqd", "AnonCreds with did:web"],
  "executionEnvironment": "cloud",
  "trustManagements": ["Trusted Lists", "Verifier knows Issuers", "X.509 certificates"],
  "urlWebsite": "https://paradym.id"
}
