=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/viewer/src/assets/schemas/wallet.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "Wallet",
  "title": "Wallet or Agent",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "description": "The schema version of the agent JSON entry"
    },
    "name": {
      "type": "string",
      "description": "The name of the agent"
    },
    "urlWebsite": {
      "type": "string",
      "description": "An URL to the website of the agent with more information",
      "format": "uri"
    },
    "logo": {
      "type": "string",
      "description": "The URL to the logo of the agent"
    },
    "company": {
      "type": "string",
      "description": "The name of the company or a community developing the agent"
    },
    "companyUrl": {
      "type": "string",
      "description": "The url to the company website (not the product website)",
      "format": "uri"
    },
    "contact": {
      "type": "string",
      "description": "A link to a contact form or an email address for support requests"
    },
    "openSource": {
      "type": "boolean",
      "description": "The agent source code is available under an open-source license"
    },
    "downloadSource": {
      "type": "string",
      "description": "The URL to the source code, for example a github repository",
      "format": "uri"
    },
    "license": {
      "type": "string",
      "description": "The license(s) of the agent source code."
    },
    "capability": {
      "type": "array",
      "description": "The capabilities supported by the agent",
      "items": {
        "type": "string",
        "enum": ["holder", "issuer", "verifier"]
      }
    },
    "executionEnvironment":  {
      "type": "string",
      "description": "Execution environment of an agent is the place where the agent is intended to be run",
      "enum": ["cloud", "edge"]
    },
    "portability": {
      "type": "boolean",
      "description": "Users can export their data from the agent and import them into another device/system"
    },
    "urlAppStore": {
      "type": "string",
      "description": "Link to the Apple AppStore",
      "format": "uri"
    },
    "urlGooglePlayStore": {
      "type": "string",
      "description": "Link to the Google Play store",
      "format": "uri"
    },
    "urlWebApp": {
      "type": "string",
      "description": "Link to the web app - where the agent can be used with a browser",
      "format": "uri"
    },
    "dependencies": {
      "type": "array",
      "description": "List of dependencies required to run the agent",
      "items": {
        "$comment": "it would help to use an enum here, but this job has to be run by each change so the enum gets updated for a valid test.",
        "type": "string"
      }
    },
    "credentialProfiles": {
      "type": "array",
      "description": "List of supported credential profiles. They entries must be valid credential profiles defined by the Credential Profiles Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Credential-Profile"
      }
    },
    "credentialFormats": {
      "type": "array",
      "description": "List of supported credential formats. They entries must be valid credential formats defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Credential%20Format",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Credential-Format"
      }
    },
    "signingAlgorithms": {
      "type": "array",
      "description": "List of supported signing algorithms. The entries must be valid algorithms defined by the Credential Formats Comparison SIG.",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Signing%20Algorithm",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Signing-Algorithm"
      }
    },
    "statusManagements": {
      "type": "array",
      "description": "List of supported status management methods. The entries must be valid status management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Status%20Algorithm",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Status-Algorithm"
      }
    },
    "keyManagements": {
      "type": "array",
      "description": "List of supported key management methods. The entries must be valid key management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Key%20Management",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Key-Management"
      }
    },
    "issuanceProtocols": {
      "type": "array",
      "description": "List of supported issuance protocols. The entries must be valid issuance protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Issuance%20Protocol",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Issuance-Protocol"
      }
    },
    "presentationProtocols": {
      "type": "array",
      "description": "List of supported presentation protocols. The entries must be valid presentation protocols defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Presentation%20Protocol",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Presentation-Protocol"
      }
    },
    "trustManagements": {
      "type": "array",
      "description": "List of supported trust management methods. The entries must be valid trust management methods defined by the Credential Formats Comparison SIG",
      "$comment": "All values can be found here: https://openwallet-foundation.github.io/credential-format-comparison-sig/#/resources/Trust%20Management",
      "items": {
        "$ref": "../viewer/src/assets/schemas/fields.json#/definitions/Trust-Management"
      }
    }
  },
  "required": ["capability", "company", "name", "urlWebsite"],
  "additionalProperties": false
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/preparese-mobile.json
{
  "capability": ["holder"],
  "company": "UFW Foundation",
  "companyUrl": "https://ufwfoundation.org/",
  "credentialFormats": ["AnonCred"],
  "credentialProfiles": ["AnonCreds with did:cheqd", "AnonCreds with did:indy"],
  "issuanceProtocols": ["Issue Credential v2"],
  "keyManagements": [
    "did:cheqd",
    "did:indy",
    "did:peer",
    "did:web",
    "link secrets"
  ],
  "license": "Proprietary",
  "name": "Preparese Mobile",
  "openSource": false,
  "portability": false,
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["CL", "EdDSA"],
  "statusManagements": [],
  "trustManagements": ["Verifier knows Issuers"],
  "executionEnvironment": "edge",
  "urlWebsite": "https://www.preparese.info/"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/eecc-verifier.json
{
  "name": "VC Verifier",
  "logo": "logos/eecc-verifier.png",
  "company": "European EPC Competence Center GmbH",
  "companyUrl": "https://id.eecc.de/products/vc_verifier.html",
  "executionEnvironment": "cloud",
  "openSource": true,
  "downloadSource": "https://github.com/european-epc-competence-center/vc-verifier",
  "license": "AGPL-3.0",
  "capability": ["verifier"],
  "portability": true,
  "urlWebsite": "https://ssi.eecc.de/verifier/",
  "credentialProfiles": [],
  "credentialFormats": ["LDP-VC", "SD-JWT-VC", "SD-JWT"],
  "issuanceProtocols": [],
  "keyManagements": ["did:jwk", "did:key", "did:web"],
  "presentationProtocols": ["OpenID4VP"],
  "signingAlgorithms": ["ECDSA", "EdDSA"],
  "statusManagements": ["Status List 2021"],
  "trustManagements": [],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/meeco-holder-wallet.json
{
  "capability": ["holder"],
  "company": "Meeco Group Pty Ltd",
  "companyUrl": "https://meeco.me/",
  "credentialFormats": ["JWT-VC", "SD-JWT-VC"],
  "credentialProfiles": [
    "EBSI",
    "HAIP",
    "JWT VC Presentation Profile",
    "SD-JWT VCs (w/ X.509 for Issuers)"
  ],
  "issuanceProtocols": ["OpenID4VCI"],
  "presentationProtocols": ["OpenID4VP"],
  "keyManagements": ["did:key", "did:jwk", "raw public keys (jwk)"],
  "license": "Commercial",
  "urlWebsite": "https://meeco.me/",
  "logo": "logos/meeco.png",
  "name": "Meeco Holder Wallet",
  "openSource": false,
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["EdDSA", "ECDSA"],
  "statusManagements": ["Status List 2021"],
  "trustManagements": ["EBSI Trust Registries", "X.509 certificates"],
  "executionEnvironment":"cloud"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/anonyome-enterprise-wallet.json
{
  "capability": ["issuer", "holder", "verifier"],
  "executionEnvironment": "cloud",
  "name": "Anonyome Enterprise Wallet",
  "logo": "logos/anonyome.png",
  "company": "Anonyome Labs",
  "companyUrl": "https://www.anonyome.com",
  "urlWebsite": "https://sudoplatform.com/verifiable-credentials/",
  "openSource": false,
  "license": "",
  "credentialProfiles": ["AnonCreds with did:indy"],
  "credentialFormats": ["AnonCred", "LDP-VC", "VC (1.1)"],
  "issuanceProtocols": ["Issue Credential v1", "Issue Credential v2"],
  "keyManagements": ["did:indy", "did:key", "did:peer", "link secrets"],
  "presentationProtocols": ["Present Proof v2", "Present Proof v1.0"],
  "signingAlgorithms": ["BBS+ with public key binding", "CL", "ECDSA", "EdDSA"],
  "statusManagements": ["Indy Revocation"],
  "trustManagements": [],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/izertis-identfy-business-wallet.json
{
  "capability": [
    "issuer",
    "holder"
  ],
  "name": "Identfy Business Wallet",
  "logo": "logos/izertis-identfy-logo-blue.png",
  "company": "Izertis, S.A.",
  "companyUrl": "https://www.izertis.com/es/",
  "urlWebsite": "https://identfy.es/",
  "openSource": false,
  "portability": false,
  "credentialProfiles": [
    "EBSI",
    "JWT VC Presentation Profile 2",
    "JWT VC Presentation Profile"
  ],
  "credentialFormats": [
    "JWT-VC",
    "JWT"
  ],
  "issuanceProtocols": [
    "OpenID4VCI"
  ],
  "keyManagements": [
    "did:ebsi",
    "did:jwk",
    "did:key"
  ],
  "presentationProtocols": [
    "OpenID4VP"
  ],
  "signingAlgorithms": [
    "ECDSA"
  ],
  "statusManagements": [
    "Status List 2021",
    "Validity Credential",
    "medium-term expiration",
    "short-term expiration"
  ],
  "trustManagements": [
    "EBSI Trust Registries"
  ],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/essif-wallet.json
{
  "capability": ["holder"],
  "company": "ESSIF Playground",
  "downloadSource": "https://github.com/majo32/sk-essif-verifier",
  "logo": "logos/essif-wallet.svg",
  "name": "ESSIF Wallet",
  "executionEnvironment": "cloud",
  "urlWebApp": "https://wallet.essif.sk/",
  "urlWebsite": "https://docs.essif.sk/en/home-english/",
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/eecc-did-controller.json
{
  "name": "DID Controller",
  "logo": "logos/eecc-did-controller.png",
  "company": "European EPC Competence Center GmbH",
  "companyUrl": "https://id.eecc.de/products/did_controller.html",
  "executionEnvironment":"cloud",
  "openSource": false,
  "capability": ["issuer", "holder"],
  "portability": false,
  "urlWebsite": "https://id.eecc.de/products/did_controller.html",
  "credentialProfiles": [],
  "credentialFormats": ["LDP-VC"],
  "issuanceProtocols": ["OpenID4VCI"],
  "keyManagements": ["did:key", "did:web"],
  "presentationProtocols": ["OpenID4VP"],
  "signingAlgorithms": ["ECDSA", "EdDSA"],
  "statusManagements": ["Status List 2021"],
  "trustManagements": ["Verifier knows Issuers"],
  "$schema": "../../schemas/wallet.json"
}

=== openwallet-foundation/digital-wallet-and-agent-overviews-sig/data/wallets/meeco-organisation-wallet.json
{
  "capability": ["issuer", "verifier"],
  "company": "Meeco Group Pty Ltd",
  "companyUrl": "https://meeco.me/",
  "credentialFormats": ["JWT-VC", "SD-JWT-VC"],
  "credentialProfiles": [
    "HAIP",
    "JWT VC Presentation Profile",
    "SD-JWT VCs (w/ X.509 for Issuers)"
  ],
  "issuanceProtocols": ["OpenID4VCI"],
  "keyManagements": [
    "did:key",
    "did:jwk",
    "did:web",
    ".well-known/jwt-issuer",
    "pub key in X.509 cert",
    "raw public keys (jwk)"
  ],
  "urlWebsite": "https://meeco.me/",
  "license": "Commercial",
  "logo": "logos/meeco.png",
  "name": "Meeco Organisation Wallet",
  "openSource": false,
  "presentationProtocols": ["OpenID4VP"],
  "$schema": "../../schemas/wallet.json",
  "signingAlgorithms": ["EdDSA", "ECDSA"],
  "statusManagements": ["Status List 2021"],
  "trustManagements": ["X.509 certificates"],
  "executionEnvironment":"cloud"
}
